
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fpl_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'fpl_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start:
  - "create extension if not exists unaccent"
  - "create extension if not exists pg_trgm"
  - "{{ create_normalize_player_name_function() }}"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  fpl_dbt:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: incremental
    serving:
      +schema: serving
      +materialized: table
    ml:
      +schema: ml
      +materialized: table

seeds:
  fpl_dbt:
    missing_teams:
      +schema: seed
      +alias: missing_teams
    team_id_map:
      +schema: seed
      +alias: team_id_map
    fpl_player_id_map:
      +schema: seed
      +alias: fpl_player_id_map
    missing_understat_id_map:
      +schema: seed
      +alias: missing_understat_id_map
