version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: fpl_bootstrap_static
        description: 'Raw data from bootstrap-static endpoint of the FPL API'
      
      - name: fpl_element_summary
        description: 'Raw data from element-summary endpoint of the FPL API'
      
      - name: fpl_fixtures
        description: 'Raw data from fixtures endpoint of the FPL API'
      
      - name: fpl_events
        description: 'Raw data from event endpoint of the FPL API'
      
      - name: vaastav_players
        description: 'Raw player data from vaastav repo'
      
      - name: vaastav_gws
        description: 'Raw player-game data from vaastav repo'
      
      - name: vaastav_fixtures
        description: 'Raw fixture data from vaastav repo'
      
      - name: vaastav_teams
        description: 'Raw team data from vaastav repo'

      - name: understat_season_data
        description: 'Raw season data from Understat'

      - name: understat_shot_data
        description: 'Raw shot data from Understat'

      - name: id_mappings
        description: 'Raw player ID mappings data extracted from GitHub repo'