version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: bootstrap_static
        description: 'Raw data from bootstrap-static endpoint of the FPL API'
      - name: element_summary
        description: 'Raw data from element-summary endpoint of the FPL API'
      - name: fixtures
        description: 'Raw data from fixtures endpoint of the FPL API'
      - name: events
        description: 'Raw data from event endpoint of the FPL API'
